on: push
name: Push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.3.0
      with:
        repotoken: ${{ secrets.GITHUB_TOKEN }}